In [1]:
import numpy as np
import matplotlib.pyplot as plt
import open3d as o3d
import k3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [11]:
src_file = "Frame2555.ply"
tgt_file = "Frame3979.ply"
src = o3d.io.read_point_cloud(src_file)
tgt = o3d.io.read_point_cloud(tgt_file)

# ファイル名から拡張子を除き, _sampled.plyをつけたものをサンプル後ファイルとする
src_sampled_file = src_file.split(".")[0] + "_sampled.ply"
tgt_sampled_file = tgt_file.split(".")[0] + "_sampled.ply"

In [3]:
# k3dを使用して可視化
plot = k3d.plot()
plot += k3d.points(np.asarray(src.points), point_size=0.01, color=0xff0000)
plot += k3d.points(np.asarray(tgt.points), point_size=0.01, color=0x0000ff)
plot.display()

c:\Users\shin0\anaconda3\envs\deeplearning\lib\site-packages\traittypes\traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


Output()

In [12]:
# downsample
src_down = o3d.io.read_point_cloud(src_sampled_file)

In [13]:
# 可視化
plot = k3d.plot()
plot += k3d.points(np.asarray(src_down.points), point_size=0.01, color=0xff0000)
plot += k3d.points(np.asarray(tgt.points), point_size=0.01, color=0x0000ff)
plot.display()

c:\Users\shin0\anaconda3\envs\deeplearning\lib\site-packages\traittypes\traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


Output()

In [6]:
src_down

PointCloud with 10000 points.

In [7]:
# 可視化
o3d.visualization.draw_geometries([src_down])

In [8]:
src_down = o3d.geometry.PointCloud()
src_down.points = o3d.utility.Vector3dVector(src_down)
tgt_down = o3d.geometry.PointCloud()
tgt_down.points = o3d.utility.Vector3dVector(tgt_down)

src_down.paint_uniform_color([1, 0.706, 0])
tgt_down.paint_uniform_color([0, 0.651, 0.929])

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cpu.pybind.utility.Vector3dVector()
    2. open3d.cpu.pybind.utility.Vector3dVector(arg0: numpy.ndarray[numpy.float64])
    3. open3d.cpu.pybind.utility.Vector3dVector(arg0: open3d.cpu.pybind.utility.Vector3dVector)
    4. open3d.cpu.pybind.utility.Vector3dVector(arg0: Iterable)

Invoked with: PointCloud with 0 points.

In [ ]:
# icp
threshold = 0.02

icp_coarse = o3d.pipelines.registration.registration_icp(
    src_down, tgt_down, threshold, np.identity(4),
    o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(icp_coarse)
print("Transformation is:")
# 指数表記を禁止
np.set_printoptions(suppress=True)
print(icp_coarse.transformation)

RegistrationResult with fitness=1.134628e-04, inlier_rmse=3.669404e-13, and correspondence_set size of 24
Access transformation to get result.
Transformation is:
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [ ]:
# draw
src.paint_uniform_color([1, 0, 0])
tgt.paint_uniform_color([0, 1, 0])
o3d.visualization.draw_geometries([src_down, tgt_down])

# draw
src.transform(icp_coarse.transformation)
o3d.visualization.draw_geometries([src_down, tgt_down])