In [1]:
import numpy as np
import matplotlib.pyplot as plt
import open3d as o3d
import k3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
src_file = "Frame2555.ply"
tgt_file = "Frame3979.ply"
src = o3d.io.read_point_cloud(src_file)
tgt = o3d.io.read_point_cloud(tgt_file)

# ファイル名から拡張子を除き, _sampled.plyをつけたものをサンプル後ファイルとする
src_sampled_file = src_file.split(".")[0] + "_sampled.ply"
tgt_sampled_file = tgt_file.split(".")[0] + "_sampled.ply"

In [3]:
# k3dを使用して可視化
plot = k3d.plot()
plot += k3d.points(np.asarray(src.points), point_size=0.01, color=0xff0000)
plot += k3d.points(np.asarray(tgt.points), point_size=0.01, color=0x0000ff)
plot.display()

c:\Users\furukawa\anaconda3\envs\Deeplearning\lib\site-packages\traittypes\traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float32". A coerced copy has been created.
  warnings.warn(


Output()

In [4]:
# downsample
src_down = o3d.io.read_point_cloud(src_sampled_file)
tgt_down = o3d.io.read_point_cloud(tgt_sampled_file)

In [5]:
# 可視化
plot = k3d.plot()
plot += k3d.points(np.asarray(src_down.points), point_size=0.01, color=0xff0000)
plot += k3d.points(np.asarray(tgt_down.points), point_size=0.01, color=0x0000ff)
plot.display()

Output()

In [6]:
src_down

PointCloud with 10000 points.

In [10]:
# ソース点群とターゲット点群, 回転行列と並進ベクトルから結果を可視化
source = o3d.io.read_point_cloud(src_sampled_file)
target = o3d.io.read_point_cloud(tgt_sampled_file)

# 回転行列と並進ベクトルを作成
R = [[1, -2.40828e-05, -1.40028e-05], 
     [2.40831e-05, 1, 1.82181e-05], 
     [1.40024e-05, -1.82185e-05, 1]]
t = [-0.00423361, 0.0170232, -0.00857199]

# 変換行列を作成
transformation = np.identity(4)
transformation[:3, :3] = R
transformation[:3, 3] = t

print(transformation)

source.transform(transformation)

# ソース点群とターゲット点群を可視化
plot = k3d.plot()
plot += k3d.points(np.asarray(source.points), point_size=0.01, color=0xff0000)
plot += k3d.points(np.asarray(target.points), point_size=0.01, color=0x0000ff)
plot.display()

[[ 1.00000e+00 -2.40828e-05 -1.40028e-05 -4.23361e-03]
 [ 2.40831e-05  1.00000e+00  1.82181e-05  1.70232e-02]
 [ 1.40024e-05 -1.82185e-05  1.00000e+00 -8.57199e-03]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]


Output()